### ISSUE TITLE
Update June screenshot

### ISSUE THREAD

**Issue by ferrucc-io** [chakra-ui/awesome-chakra-ui#42]
The june screenshot here: https://chakra-ui.com/showcase

Is an old version of our site which is ugly, this is prettier to look at
<img width="1512" alt="Screenshot 2022-04-01 at 14 48 29" src="https://user-images.githubusercontent.com/8315559/161266711-02e17230-760b-43dc-96e0-4c521c42bb36.png">

**Comment by nikolovlazar** [comment]
Done! Check it out, @ferrucc-io: [https://chakra-ui.com](https://chakra-ui.com)!
