### ISSUE TITLE
some website  can't be open

### ISSUE THREAD

**Issue by zxhycxq** [chakra-ui/awesome-chakra-ui#76]
![image](https://user-images.githubusercontent.com/11674203/190961447-8767d578-19d1-491e-b6e8-8b1a9a68d1d5.png)

https://chakra-play.tk/

`https://chakra-play.tk/`

It was wrong. may be the website was expired。

**Comment by nikolovlazar** [comment]
Yes, it seems that its certificate has expired. I'll remove it. Thanks!
